# Docker Composeのバージョン指定
version: '3'

# サービス(コンテナ)の定義
services:
  db:
    image: mysql:8.1
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: team_development_app_container
    tty: true
    stdin_open: true
    volumes:
      # ホストのカレントディレクトリをコンテナの作業ディレクトリにマウント
      - .:/team_development_app
      # gemを保存するボリュームをマウント
      - bundle_data:/usr/local/bundle:cached
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  # ブラウザ（Selenium用）のコンテナ
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
# ボリュームの定義
volumes:
  mysql_data:
  bundle_data:

# ボリュームのマウントとは？
# アプリケーションのデータ管理や永続化、コンテナ間のデータ共有などで使用する
# 特に、データベース、設定ファイル、ログファイル、アプリケーションコードなどを永続化するために頻繁に利用される。